package me.yricky.oh.abcd.isa

import me.yricky.oh.abcd.isa.InsFmt.Companion.NONE

/**
 * 方舟字节码指令集
 */
sealed class Ins(
    val opCode:Byte,
    val symbol: String
){
    companion object{
        private inline fun b(value:Int) = value.toByte()
        val INS_MAP = mapOf<Byte,Ins>(
            b(0x0) to Ins1(0x0,NONE,"ldUndefined"),
            b(0x1) to Ins1(0x1,NONE,"ldNull"),
            b(0x2) to Ins1(0x2,NONE,"ldTrue"),
            b(0x3) to Ins1(0x3,NONE,"ldFalse"),
            b(0x4) to Ins1(0x4,NONE,"createEmptyObject"),
            b(0x5) to Ins1(0x5,InsFmt.fromString("IMM8"),"createEmptyArray"),
            b(0x6) to Ins1(0x6,InsFmt.fromString("IMM8_LID16"),"createArrayWithBuffer"),
            b(0x7) to Ins1(0x7,InsFmt.fromString("IMM8_LID16"),"createObjectWithBuffer"),
            b(0x8) to Ins1(0x8,InsFmt.fromString("IMM8_IMM8_V8"),"newObjRange"),
            b(0x9) to Ins1(0x9,InsFmt.fromString("IMM8"),"newLexEnv"),
            b(0xa) to Ins1(0xa,InsFmt.fromString("IMM8_V8"),"add2"),
            b(0xb) to Ins1(0xb,InsFmt.fromString("IMM8_V8"),"sub2"),
            b(0xc) to Ins1(0xc,InsFmt.fromString("IMM8_V8"),"mul2"),
            b(0xd) to Ins1(0xd,InsFmt.fromString("IMM8_V8"),"div2"),
            b(0xe) to Ins1(0xe,InsFmt.fromString("IMM8_V8"),"mod2"),
            b(0xf) to Ins1(0xf,InsFmt.fromString("IMM8_V8"),"eq"),

            b(0x10) to Ins1(0x10,InsFmt.fromString("IMM8_V8"),"notEq"),
            b(0x11) to Ins1(0x11,InsFmt.fromString("IMM8_V8"),"less"),
            b(0x12) to Ins1(0x12,InsFmt.fromString("IMM8_V8"),"lessEq"),
            b(0x13) to Ins1(0x13,InsFmt.fromString("IMM8_V8"),"greater"),
            b(0x14) to Ins1(0x14,InsFmt.fromString("IMM8_V8"),"greaterEq"),
            b(0x15) to Ins1(0x15,InsFmt.fromString("IMM8_V8"),"shl2"),
            b(0x16) to Ins1(0x16,InsFmt.fromString("IMM8_V8"),"shr2"),
            b(0x17) to Ins1(0x17,InsFmt.fromString("IMM8_V8"),"ashr2"),
            b(0x18) to Ins1(0x18,InsFmt.fromString("IMM8_V8"),"and2"),
            b(0x19) to Ins1(0x19,InsFmt.fromString("IMM8_V8"),"or2"),
            b(0x1a) to Ins1(0x1a,InsFmt.fromString("IMM8_V8"),"xor2"),
            b(0x1b) to Ins1(0x1b,InsFmt.fromString("IMM8_V8"),"exp"),
            b(0x1c) to Ins1(0x1c,InsFmt.fromString("IMM8"),"typeOf"),
            b(0x1d) to Ins1(0x1d,InsFmt.fromString("IMM8"),"toNumber"),
            b(0x1e) to Ins1(0x1e,InsFmt.fromString("IMM8"),"toNumeric"),
            b(0x1f) to Ins1(0x1f,InsFmt.fromString("IMM8"),"neg"),

            b(0x20) to Ins1(0x20,InsFmt.fromString("IMM8"),"not"),
            b(0x21) to Ins1(0x21,InsFmt.fromString("IMM8"),"inc"),
            b(0x22) to Ins1(0x22,InsFmt.fromString("IMM8"),"dec"),
            b(0x23) to Ins1(0x23,NONE,"isTrue"),
            b(0x24) to Ins1(0x24,NONE,"isFalse"),
            b(0x25) to Ins1(0x25,InsFmt.fromString("IMM8_V8"),"isIn"),
            b(0x26) to Ins1(0x26,InsFmt.fromString("IMM8_V8"),"instanceOf"),
            b(0x27) to Ins1(0x27,InsFmt.fromString("IMM8_V8"),"strictNotEq"),
            b(0x28) to Ins1(0x28,InsFmt.fromString("IMM8_V8"),"strictEq"),
            b(0x29) to Ins1(0x29,InsFmt.fromString("IMM8"),"callArg0"),
            b(0x2a) to Ins1(0x2a,InsFmt.fromString("IMM8_V8"),"callArg1"),
            b(0x2b) to Ins1(0x2b,InsFmt.fromString("IMM8_V8_V8"),"callArg2"),
            b(0x2c) to Ins1(0x2c,InsFmt.fromString("IMM8_V8_V8_V8"),"callArg3"),
            b(0x2d) to Ins1(0x2d,InsFmt.fromString("IMM8_V8"),"callThis0"),
            b(0x2e) to Ins1(0x2e,InsFmt.fromString("IMM8_V8_V8"),"callThis1"),
            b(0x2f) to Ins1(0x2f,InsFmt.fromString("IMM8_V8_V8_V8"),"callThis2"),

            b(0x30) to Ins1(0x30,InsFmt.fromString("IMM8_V8_V8_V8_V8"),"callThis3"),
            b(0x31) to Ins1(0x31,InsFmt.fromString("IMM8_IMM8_V8"),"callThisRange"),
            b(0x32) to Ins1(0x32,InsFmt.fromString("IMM8_IMM8_V8"),"superCallThisRange"),
            b(0x33) to Ins1(0x33,InsFmt.fromString("IMM8_MID16_IMM8"),"defineFunc"),
            b(0x34) to Ins1(0x34,InsFmt.fromString("IMM8_MID16_IMM8"),"defineMethod"),
            b(0x35) to Ins1(0x35,InsFmt.fromString("IMM8_MID16_LID16_IMM16_V8"),"defineClassWithBuffer"),
            b(0x36) to Ins1(0x36,InsFmt.fromString("V8"),"getNextPropName"),
            b(0x37) to Ins1(0x37,InsFmt.fromString("IMM8_V8"),"ldObjByValue"),
            b(0x38) to Ins1(0x38,InsFmt.fromString("IMM8_V8_V8"),"stObjByValue"),
            b(0x39) to Ins1(0x39,InsFmt.fromString("IMM8_V8"),"ldSuperByValue"),
            b(0x3a) to Ins1(0x3a,InsFmt.fromString("IMM8_IMM16"),"ldObjByIndex"),
            b(0x3b) to Ins1(0x3b,InsFmt.fromString("IMM8_V8_IMM16"),"stObjByIndex"),
            b(0x3c) to Ins1(0x3c,InsFmt.fromString("IMM4_IMM4"),"ldLexVar"),
            b(0x3d) to Ins1(0x3d,InsFmt.fromString("IMM4_IMM4"),"stLexVar"),
            b(0x3e) to Ins1(0x3e,InsFmt.fromString("SID16"),"lda.str"),
            b(0x3f) to Ins1(0x3f,InsFmt.fromString("IMM8_SID16"),"tryLdGlobalByName"),

            b(0x40) to Ins1(0x40,InsFmt.fromString("IMM8_SID16"),"tryStGlobalByName"),
            b(0x41) to Ins1(0x41,InsFmt.fromString("IMM16_SID16"),"ldGlobalVar"),
            b(0x42) to Ins1(0x42,InsFmt.fromString("IMM8_SID16"),"ldObjByName"),
            b(0x43) to Ins1(0x43,InsFmt.fromString("IMM8_SID16_V8"),"stObjByName"),
            b(0x44) to Ins1(0x44,InsFmt.fromString("V4_V4"),"mov"),
            b(0x45) to Ins1(0x45,InsFmt.fromString("V8_V8"),"mov"),
            b(0x46) to Ins1(0x46,InsFmt.fromString("IMM8_SID16"),"ldSuperByName"),
            b(0x47) to Ins1(0x47,InsFmt.fromString("IMM16_SID16"),"stConstToGlobalRecord"),
            b(0x48) to Ins1(0x48,InsFmt.fromString("IMM16_SID16"),"stToGlobalRecord"),
            b(0x49) to Ins1(0x49,InsFmt.fromString("IMM8_SID16"),"ldThisByName"),
            b(0x4a) to Ins1(0x4a,InsFmt.fromString("IMM8_SID16"),"stThisByName"),
            b(0x4b) to Ins1(0x4b,InsFmt.fromString("IMM8"),"ldThisByValue"),
            b(0x4c) to Ins1(0x4c,InsFmt.fromString("IMM8_V8"),"stThisByValue"),
            b(0x4d) to Ins1(0x4d,InsFmt.fromString("IMM8"),"jmp"),
            b(0x4e) to Ins1(0x4e,InsFmt.fromString("IMM16"),"jmp"),
            b(0x4f) to Ins1(0x4f,InsFmt.fromString("IMM8"),"jEqz"),

            b(0x50) to Ins1(0x50,InsFmt.fromString("IMM16"),"jEqz"),
            b(0x51) to Ins1(0x51,InsFmt.fromString("IMM8"),"jNez"),
            b(0x52) to Ins1(0x52,InsFmt.fromString("IMM8"),"jStrictEqz"),
            b(0x53) to Ins1(0x53,InsFmt.fromString("IMM8"),"jStrictEqz"),
            b(0x54) to Ins1(0x54,InsFmt.fromString("IMM8"),"jEqNull"),
            b(0x55) to Ins1(0x55,InsFmt.fromString("IMM8"),"jEqNull"),
            b(0x56) to Ins1(0x56,InsFmt.fromString("IMM8"),"jStrictEqNull"),
            b(0x57) to Ins1(0x57,InsFmt.fromString("IMM8"),"jStrictEqNull"),
            b(0x58) to Ins1(0x58,InsFmt.fromString("IMM8"),"jEqUndefined"),
            b(0x59) to Ins1(0x59,InsFmt.fromString("IMM8"),"jEqUndefined"),
            b(0x5a) to Ins1(0x5a,InsFmt.fromString("IMM8"),"jStrictEqUndefined"),
            b(0x5b) to Ins1(0x5b,InsFmt.fromString("IMM8"),"jStrictEqUndefined"),
            b(0x5c) to Ins1(0x5c,InsFmt.fromString("V8_IMM8"),"jeq"),
            b(0x5d) to Ins1(0x5d,InsFmt.fromString("V8_IMM8"),"jne"),
            b(0x5e) to Ins1(0x5e,InsFmt.fromString("V8_IMM8"),"jStrictEq"),
            b(0x5f) to Ins1(0x5f,InsFmt.fromString("V8_IMM8"),"jStrictEq"),

            b(0x60) to Ins1(0x60,InsFmt.fromString("V8"),"lda"),
            b(0x61) to Ins1(0x61,InsFmt.fromString("V8"),"sta"),
            b(0x62) to Ins1(0x62,InsFmt.fromString("IMM32"),"ldai"),
            b(0x63) to Ins1(0x63,InsFmt.fromString("IMM64"),"fldai"),
            b(0x64) to Ins1(0x64, NONE,"return"),
            b(0x65) to Ins1(0x65, NONE,"returnUndefined"),
            b(0x66) to Ins1(0x66, NONE,"getPropIterator"),
            b(0x67) to Ins1(0x67,InsFmt.fromString("IMM8"),"getIterator"),
            b(0x68) to Ins1(0x68,InsFmt.fromString("IMM8_V8"),"closeIterator"),
            b(0x69) to Ins1(0x69, NONE,"popLexEnv"),
            b(0x6a) to Ins1(0x6a, NONE,"ldNan"),
            b(0x6b) to Ins1(0x6b, NONE,"ldInfinity"),
            b(0x6c) to Ins1(0x6c, NONE,"getUnmappedArgs"),
            b(0x6d) to Ins1(0x6d, NONE,"ldGlobal"),
            b(0x6e) to Ins1(0x6e, NONE,"ldNewTarget"),
            b(0x6f) to Ins1(0x6f, NONE,"ldThis"),

            b(0x70) to Ins1(0x70, NONE,"ldHole"),
            b(0x71) to Ins1(0x71,InsFmt.fromString("IMM8_SID16_IMM8"),"createRegexpWithLiteral"),
            b(0x72) to Ins1(0x72,InsFmt.fromString("IMM16_SID16_IMM8"),"createRegexpWithLiteral"),
            b(0x73) to Ins1(0x73,InsFmt.fromString("IMM8_IMM8_V8"),"callRange"),
            b(0x74) to Ins1(0x74,InsFmt.fromString("IMM16_MID16_IMM8"),"defineFunc"),
            b(0x75) to Ins1(0x75,InsFmt.fromString("IMM16_MID16_LID16_IMM16_V8"),"defineClassWithBuffer"),
            b(0x76) to Ins1(0x76,InsFmt.fromString("IMM8"),"getTemplateObject"),
            b(0x77) to Ins1(0x77,InsFmt.fromString("IMM8_V8"),"setObjectWithProto"),
            b(0x78) to Ins1(0x78,InsFmt.fromString("IMM8_V8_V8"),"stOwnByValue"),
            b(0x79) to Ins1(0x79,InsFmt.fromString("IMM8_V8_IMM16"),"stOwnByIndex"),
            b(0x7a) to Ins1(0x7a,InsFmt.fromString("IMM8_SID16_V8"),"stOwnByName"),
            b(0x7b) to Ins1(0x7b,InsFmt.fromString("IMM8"),"getModuleNamespace"),
            b(0x7c) to Ins1(0x7c,InsFmt.fromString("IMM8"),"stModuleVar"),
            b(0x7d) to Ins1(0x7d,InsFmt.fromString("IMM8"),"ldLocalModuleVar"),
            b(0x7e) to Ins1(0x7e,InsFmt.fromString("IMM8"),"ldExternalModuleVar"),
            b(0x7f) to Ins1(0x7f,InsFmt.fromString("IMM16_SID16"),"stGlobalVar"),

            b(0x80) to Ins1(b(0x80),InsFmt.fromString("IMM16"),"createEmptyArray"),
            b(0x81) to Ins1(b(0x81),InsFmt.fromString("IMM16_LID16"),"createArrayWithBuffer"),
            b(0x82) to Ins1(b(0x82),InsFmt.fromString("IMM16_LID16"),"createObjectWithBuffer"),
            b(0x83) to Ins1(b(0x83),InsFmt.fromString("IMM16_IMM8_V8"),"newObjRange"),
            b(0x84) to Ins1(b(0x84),InsFmt.fromString("IMM16"),"typeOf"),
            b(0x85) to Ins1(b(0x85),InsFmt.fromString("IMM16_V8"),"ldObjByValue"),
            b(0x86) to Ins1(b(0x86),InsFmt.fromString("IMM16_V8_V8"),"stObjByValue"),
            b(0x87) to Ins1(b(0x87),InsFmt.fromString("IMM16_V8"),"ldSuperByValue"),
            b(0x88) to Ins1(b(0x88),InsFmt.fromString("IMM16_IMM16"),"ldObjByIndex"),
            b(0x89) to Ins1(b(0x89),InsFmt.fromString("IMM16_V8_IMM16"),"stObjByIndex"),
            b(0x8a) to Ins1(b(0x8a),InsFmt.fromString("IMM8_IMM8"),"ldLexVar"),
            b(0x8b) to Ins1(b(0x8b),InsFmt.fromString("IMM8_IMM8"),"stLexVar"),
            b(0x8c) to Ins1(b(0x8c),InsFmt.fromString("IMM16_SID16"),"tryLdGlobalByName"),
            b(0x8d) to Ins1(b(0x8d),InsFmt.fromString("IMM16_SID16"),"tryStGlobalByName"),
            b(0x8e) to Ins1(b(0x8e),InsFmt.fromString("IMM8_SID16_V8"),"stOwnByNameWithNameSet"),
            b(0x8f) to Ins1(b(0x8f),InsFmt.fromString("V16_V16"),"mov"),

            b(0x90) to Ins1(b(0x90),InsFmt.fromString("IMM16_SID16"),"lsObjByName"),
            b(0x91) to Ins1(b(0x91),InsFmt.fromString("IMM16_SID16_V8"),"stObjByName"),
            b(0x92) to Ins1(b(0x92),InsFmt.fromString("IMM16_SID16"),"ldSuperByName"),
            b(0x93) to Ins1(b(0x93),InsFmt.fromString("IMM16_SID16"),"ldThisByName"),
            b(0x94) to Ins1(b(0x94),InsFmt.fromString("IMM16_SID16"),"stThisByName"),
            b(0x95) to Ins1(b(0x95),InsFmt.fromString("IMM16"),"ldThisByValue"),
            b(0x96) to Ins1(b(0x96),InsFmt.fromString("IMM16_V8"),"stThisByValue"),
            b(0x97) to Ins1(b(0x97),InsFmt.fromString("V8"),"asyncGeneratorReject"),
            b(0x98) to Ins1(b(0x98),InsFmt.fromString("IMM32"),"jmp"),
            b(0x99) to Ins1(b(0x99),InsFmt.fromString("IMM8_V8_V8"),"stOwnByValueWithNameSet"),
            b(0x9a) to Ins1(b(0x9a),InsFmt.fromString("IMM32"),"jEqz"),
            b(0x9b) to Ins1(b(0x9b),InsFmt.fromString("IMM16"),"jNez"),
            b(0x9c) to Ins1(b(0x9c),InsFmt.fromString("IMM32"),"jNez"),
            b(0x9d) to Ins1(b(0x9d),InsFmt.fromString("IMM16"),"jStrictEqz"),
            b(0x9e) to Ins1(b(0x9e),InsFmt.fromString("IMM16"),"jnStrictEqz"),
            b(0x9f) to Ins1(b(0x9f),InsFmt.fromString("IMM16"),"jeqNull"),

            b(0xa0) to Ins1(b(0xa0),InsFmt.fromString("IMM16"),"jStrictEqNull"),
            b(0xa1) to Ins1(b(0xa1),InsFmt.fromString("IMM16"),"jnStrictEqNull"),
            b(0xa2) to Ins1(b(0xa2),InsFmt.fromString("IMM16"),"ldSuperByName"),
            b(0xa3) to Ins1(b(0xa3),InsFmt.fromString("IMM16"),"jeqUndefined"),
            b(0xa4) to Ins1(b(0xa4),InsFmt.fromString("IMM16"),"jneUndefined"),
            b(0xa5) to Ins1(b(0xa5),InsFmt.fromString("IMM16"),"jStrictEqUndefined"),
            b(0xa6) to Ins1(b(0xa6),InsFmt.fromString("IMM16"),"jnStrictEqUndefined"),
            b(0xa7) to Ins1(b(0xa7),InsFmt.fromString("V8_IMM16"),"jeq"),
            b(0xa8) to Ins1(b(0xa8),InsFmt.fromString("V8_IMM16"),"jne"),
            b(0xa9) to Ins1(b(0xa9),InsFmt.fromString("V8_IMM16"),"jStrictEq"),
            b(0xaa) to Ins1(b(0xaa),InsFmt.fromString("V8_IMM16"),"jnStrictEq"),
            b(0xab) to Ins1(b(0xab),InsFmt.fromString("IMM16"),"getIterator"),
            b(0xac) to Ins1(b(0xac),InsFmt.fromString("IMM16_V8"),"closeIterator"),
            b(0xad) to Ins1(b(0xad), NONE,"ldSymbol"),
            b(0xae) to Ins1(b(0xae), NONE,"asyncFunctionEnter"),
            b(0xaf) to Ins1(b(0xaf), NONE,"ldFunction"),

            b(0xb0) to Ins1(b(0xb0), NONE,"debugger"),
            b(0xb1) to Ins1(b(0xb1),InsFmt.fromString("V8"),"createGeneratorObj"),
            b(0xb2) to Ins1(b(0xb2),InsFmt.fromString("V8_V8"),"createIterResultObj"),
            b(0xb3) to Ins1(b(0xb3),InsFmt.fromString("IMM8_V8_V8"),"createObjectWithExcludedKeys"),
            b(0xb4) to Ins1(b(0xb4),InsFmt.fromString("IMM8_V8"),"newObjApply"),
            b(0xb5) to Ins1(b(0xb5),InsFmt.fromString("IMM16_V8"),"newObjApply"),
            b(0xb6) to Ins1(b(0xb6),InsFmt.fromString("IMM8_LID16"),"newLexEnvWithName"),
            b(0xb7) to Ins1(b(0xb7),InsFmt.fromString("V8"),"createAsyncGeneratorObj"),
            b(0xb8) to Ins1(b(0xb8),InsFmt.fromString("V8_V8_V8"),"asyncGeneratorResolve"),
            b(0xb9) to Ins1(b(0xb9),InsFmt.fromString("IMM8_V8"),"superCallSpread"),
            b(0xba) to Ins1(b(0xba),InsFmt.fromString("IMM8_V8_V8"),"apply"),
            b(0xbb) to Ins1(b(0xbb),InsFmt.fromString("IMM8_IMM8_V8"),"superCallArrowRange"),
            b(0xbc) to Ins1(b(0xbc),InsFmt.fromString("V8_V8_V8_V8"),"defineGetterSetterbyValue"),
            b(0xbd) to Ins1(b(0xbd), NONE,"dynamicImport"),
            b(0xbe) to Ins1(b(0xbe),InsFmt.fromString("IMM16_MID16_IMM8"),"defineMethod"),
            b(0xbf) to Ins1(b(0xbf), NONE,"resumeGenerator"),

            b(0xc0) to Ins1(b(0xc0), NONE,"getResumeMode"),
            b(0xc1) to Ins1(b(0xc1),InsFmt.fromString("IMM16"),"getTemplateObject"),
            b(0xc2) to Ins1(b(0xc2),InsFmt.fromString("V8"),"delObjProp"),
            b(0xc3) to Ins1(b(0xc3),InsFmt.fromString("V8"),"suspendGenerator"),
            b(0xc4) to Ins1(b(0xc4),InsFmt.fromString("V8"),"asyncFunctionAwaitUncaught"),
            b(0xc5) to Ins1(b(0xc5),InsFmt.fromString("V8"),"copyDataProperties"),
            b(0xc6) to Ins1(b(0xc6),InsFmt.fromString("V8_V8"),"stArraySpread"),
            b(0xc7) to Ins1(b(0xc7),InsFmt.fromString("IMM16_V8"),"setObjectWithProto"),
            b(0xc8) to Ins1(b(0xc8),InsFmt.fromString("IMM16_V8_V8"),"stOwnByValue"),
            b(0xc9) to Ins1(b(0xc9),InsFmt.fromString("IMM8_V8_V8"),"stSuperByValue"),
            b(0xca) to Ins1(b(0xca),InsFmt.fromString("IMM16_V8_V8"),"stSuperByValue"),
            b(0xcb) to Ins1(b(0xcb),InsFmt.fromString("IMM16_V8_IMM16"),"stOwnByIndex"),
            b(0xcc) to Ins1(b(0xcc),InsFmt.fromString("IMM16_SID16_V8"),"stOwnByName"),
            b(0xcd) to Ins1(b(0xcd),InsFmt.fromString("V8"),"asyncFunctionResolve"),
            b(0xce) to Ins1(b(0xce),InsFmt.fromString("V8"),"asyncFunctionReject"),
            b(0xcf) to Ins1(b(0xcf),InsFmt.fromString("IMM8"),"copyRestArgs"),

            b(0xd0) to Ins1(b(0xd0),InsFmt.fromString("IMM8_SID16_V8"),"stSuperByName"),
            b(0xd1) to Ins1(b(0xd1),InsFmt.fromString("IMM16_SID16_V8"),"stSuperByName"),
            b(0xd2) to Ins1(b(0xd2),InsFmt.fromString("IMM16_V8_V8"),"stOwnByValueWithNameSet"),
            b(0xd3) to Ins1(b(0xd3),InsFmt.fromString("SID16"),"ldBigInt"),
            b(0xd4) to Ins1(b(0xd4),InsFmt.fromString("IMM16_SID16_V8"),"stOwnByNameWithNameSet"),
            b(0xd5) to Ins1(b(0xd5), NONE,"nop"),
            b(0xd6) to Ins1(b(0xd6),InsFmt.fromString("IMM8"),"setGeneratorState"),
            b(0xd7) to Ins1(b(0xd7),InsFmt.fromString("IMM8"),"getAsyncIterator"),
            b(0xd8) to Ins1(b(0xd8),InsFmt.fromString("IMM8_IMM16_IMM16"),"ldPrivateProperty"),
            b(0xd9) to Ins1(b(0xd9),InsFmt.fromString("IMM8_IMM16_IMM16_V8"),"stPrivateProperty"),
            b(0xda) to Ins1(b(0xda),InsFmt.fromString("IMM8_IMM16_IMM16"),"testIn"),
            b(0xdb) to Ins1(b(0xdb),InsFmt.fromString("IMM8_SID16_V8"),"defineFieldByName"),

            b(0xfb) to Ins2(b(0xfb),"callRuntime",mapOf(
                b(0x00) to Ins1(b(0x00), NONE,"notifyConcurrentResult"),
                b(0x01) to Ins1(b(0x01),InsFmt.fromString("IMM8_V8_V8"),"defineFieldByValue"),
                b(0x02) to Ins1(b(0x02),InsFmt.fromString("IMM8_IMM32_V8"),"defineFieldByIndex"),
                b(0x03) to Ins1(b(0x03), NONE,"toPropertyKey"),
                b(0x04) to Ins1(b(0x04),InsFmt.fromString("IMM16_LID16"),"createPrivateProperty"),
                b(0x05) to Ins1(b(0x05),InsFmt.fromString("IMM8_IMM16_IMM16_V8"),"definePrivateProperty"),
                b(0x06) to Ins1(b(0x06),InsFmt.fromString("IMM8_V8"),"callInit"),
                b(0x07) to Ins1(b(0x07),InsFmt.fromString("IMM16_MID16_LID16_IMM16_V8"),"defineSendableClass"),
                b(0x08) to Ins1(b(0x08),InsFmt.fromString("IMM16"),"ldSendableClass"),)
            ),

            b(0xfd) to Ins2(b(0xfd),"wide",mapOf(
                b(0x00) to Ins1(b(0x00),InsFmt.fromString("IMM16_V8_V8"),"createObjectWithExcludedKeys"),
                b(0x01) to Ins1(b(0x01),InsFmt.fromString("IMM16_V8"),"newObjRange"),
                b(0x02) to Ins1(b(0x02),InsFmt.fromString("IMM16"),"newLexEnv"),
                b(0x03) to Ins1(b(0x03),InsFmt.fromString("IMM16_LID16"),"newLexEnvWithName"),
                b(0x04) to Ins1(b(0x04),InsFmt.fromString("IMM16_V8"),"callRange"),
                b(0x05) to Ins1(b(0x05),InsFmt.fromString("IMM16_V8"),"callThisRange"),
                b(0x06) to Ins1(b(0x06),InsFmt.fromString("IMM16_V8"),"superCallThisRange"),
                b(0x07) to Ins1(b(0x07),InsFmt.fromString("IMM16_V8"),"superCallArrowRange"),
                b(0x08) to Ins1(b(0x08),InsFmt.fromString("IMM32"),"ldObjByIndex"),
                b(0x09) to Ins1(b(0x09),InsFmt.fromString("V8_IMM32"),"stObjByIndex"),
                b(0x0a) to Ins1(b(0x0a),InsFmt.fromString("V8_IMM32"),"stOwnByIndex"),
                b(0x0b) to Ins1(b(0x0b),InsFmt.fromString("IMM16"),"copyRestArgs"),
                b(0x0c) to Ins1(b(0x0c),InsFmt.fromString("IMM16_IMM16"),"ldLexVar"),
                b(0x0d) to Ins1(b(0x0d),InsFmt.fromString("IMM16_IMM16"),"stLexVar"),
                b(0x0e) to Ins1(b(0x0e),InsFmt.fromString("IMM16"),"getModuleNameSpace"),
                b(0x0f) to Ins1(b(0x0f),InsFmt.fromString("IMM16"),"stModuleVar"),

                b(0x10) to Ins1(b(0x10),InsFmt.fromString("IMM16"),"ldLocalModuleVar"),
                b(0x11) to Ins1(b(0x11),InsFmt.fromString("IMM16"),"ldExternalmoduleVar"),
                b(0x12) to Ins1(b(0x12),InsFmt.fromString("IMM16"),"ldPatchVar"),
                b(0x13) to Ins1(b(0x13),InsFmt.fromString("IMM16"),"stPatchVar"),)
            ),

            b(0xfe) to Ins2(b(0xfe),"throw",mapOf(
                b(0x00) to Ins1(b(0x00), NONE,"throw"),
                b(0x01) to Ins1(b(0x01), NONE,"notExists"),
                b(0x02) to Ins1(b(0x02), NONE,"patternNonCoercible"),
                b(0x03) to Ins1(b(0x03), NONE,"deleteSuperProperty"),
                b(0x04) to Ins1(b(0x04),InsFmt.fromString("V8"),"constAssignment"),
                b(0x05) to Ins1(b(0x05),InsFmt.fromString("V8"),"ifNotObject"),
                b(0x06) to Ins1(b(0x06),InsFmt.fromString("V8_V8"),"undefinedIfHole"),
                b(0x07) to Ins1(b(0x07),InsFmt.fromString("IMM8"),"ifSuperNotCorrectCall"),
                b(0x08) to Ins1(b(0x08),InsFmt.fromString("IMM16"),"ifSuperNotCorrectCall"),
                b(0x09) to Ins1(b(0x09),InsFmt.fromString("SID16"),"undefinedIfHoleWithName"),)
            ),
            )
    }
    class Ins1(
        opCode:Byte,
        val fmt:InsFmt,
        symbol:String,
    ):Ins(opCode,symbol){
        fun argSize() = fmt.units.fold(0){ s,f -> s + f.size }
    }

    class Ins2(
        opCode:Byte,
        symbol:String,
        val map: Map<Byte,Ins1>
    ):Ins(opCode,symbol)
}